version: "2"

services:
  mongo:
    image: mongo
    ports:
        - "27017:27017"
    logging:
        driver: none
  webapp:
    image: webapp
    ports:
        - "8080:8080"
    volumes:
        - ./config/config.yaml:/webapp/config.yaml